use crate::desktop_agent_types::{
    CapabilityManifest, CapabilityRuntimeState, CapabilityToolAvailability, Permission,
};
use serde::Serialize;

const CONTEXT_VERSION: &str = "astra_assistant_capability_context_v2";

#[derive(Debug, Serialize)]
pub struct AssistantCapabilityContextV2 {
    pub version: &'static str,
    pub facts: AssistantCapabilityFacts,
    pub instructions: AssistantCapabilityInstructions,
}

#[derive(Debug, Serialize)]
pub struct AssistantCapabilityFacts {
    pub tools: Vec<AssistantToolFact>,
    pub screen: AssistantScreenFact,
    pub approvals: AssistantApprovalFact,
    pub policy: AssistantPolicyFact,
}

#[derive(Debug, Serialize)]
pub struct AssistantToolFact {
    pub tool_name: String,
    pub state: CapabilityRuntimeState,
    pub enabled: bool,
    pub requires_approval: bool,
    pub disabled_reason: Option<String>,
}

#[derive(Debug, Serialize)]
pub struct AssistantScreenFact {
    pub observation_supported: bool,
    pub observation_enabled: bool,
    pub capture_available: bool,
    pub fresh_capture_available: bool,
    pub fresh_capture_requires_observation_enabled: bool,
    pub analysis_available: bool,
    pub vision_model_available: bool,
    pub vision_model_name: Option<String>,
    pub recent_capture_available: bool,
    pub recent_capture_age_ms: Option<u64>,
    pub provider: String,
    pub note: String,
}

#[derive(Debug, Serialize)]
pub struct AssistantApprovalFact {
    pub pending_count: usize,
    pub approval_required_for_high_risk: bool,
    pub pending_tools: Vec<String>,
}

#[derive(Debug, Serialize)]
pub struct AssistantPolicyFact {
    pub browser_enabled: bool,
    pub desktop_control_enabled: bool,
    pub allowed_roots_count: usize,
    pub terminal_allowed_commands: Vec<String>,
    pub enabled_permissions: Vec<&'static str>,
}

#[derive(Debug, Serialize)]
pub struct AssistantCapabilityInstructions {
    pub identity: &'static str,
    pub behavior_rules: Vec<&'static str>,
}

pub fn build_capability_context(manifest: &CapabilityManifest) -> String {
    let context = build_capability_context_v2(manifest);
    let facts = serde_json::to_string_pretty(&context.facts).unwrap_or_else(|_| "{}".into());
    let rules = context
        .instructions
        .behavior_rules
        .iter()
        .enumerate()
        .map(|(index, rule)| format!("{}. {}", index + 1, rule))
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        concat!(
            "Astra capability context version: {version}\n",
            "Runtime facts, generated by Rust and safe to rely on:\n",
            "{facts}\n",
            "Behavior rules:\n",
            "{rules}"
        ),
        version = context.version,
        facts = facts,
        rules = rules,
    )
}

pub fn build_capability_context_v2(manifest: &CapabilityManifest) -> AssistantCapabilityContextV2 {
    AssistantCapabilityContextV2 {
        version: CONTEXT_VERSION,
        facts: AssistantCapabilityFacts {
            tools: manifest
                .tools
                .iter()
                .map(|tool| AssistantToolFact {
                    tool_name: tool.tool_name.clone(),
                    state: tool.state.clone(),
                    enabled: tool.enabled,
                    requires_approval: tool.requires_approval,
                    disabled_reason: tool.disabled_reason.clone(),
                })
                .collect(),
            screen: AssistantScreenFact {
                observation_supported: manifest.screen.observation_supported,
                observation_enabled: manifest.screen.observation_enabled,
                capture_available: manifest.screen.capture_available,
                fresh_capture_available: manifest.screen.fresh_capture_available,
                fresh_capture_requires_observation_enabled: manifest
                    .screen
                    .fresh_capture_requires_observation_enabled,
                analysis_available: manifest.screen.analysis_available,
                vision_model_available: manifest.screen.vision_model_available,
                vision_model_name: manifest.screen.vision_model_name.clone(),
                recent_capture_available: manifest.screen.recent_capture_available,
                recent_capture_age_ms: manifest.screen.recent_capture_age_ms,
                provider: manifest.screen.provider.clone(),
                note: manifest.screen.note.clone(),
            },
            approvals: AssistantApprovalFact {
                pending_count: manifest.approvals.pending_count,
                approval_required_for_high_risk: manifest.approvals.approval_required_for_high_risk,
                pending_tools: manifest
                    .approvals
                    .pending_actions
                    .iter()
                    .map(|approval| approval.tool_name.clone())
                    .collect(),
            },
            policy: AssistantPolicyFact {
                browser_enabled: manifest.permissions.browser_enabled,
                desktop_control_enabled: manifest.permissions.desktop_control_enabled,
                allowed_roots_count: manifest.permissions.allowed_roots.len(),
                terminal_allowed_commands: manifest.permissions.terminal_allowed_commands.clone(),
                enabled_permissions: manifest
                    .permissions
                    .allowed_permissions
                    .iter()
                    .map(permission_name)
                    .collect(),
            },
        },
        instructions: AssistantCapabilityInstructions {
            identity: "Astra is a governed local desktop assistant. Rust validates every capability and tool action.",
            behavior_rules: vec![
                "Do not deny local capabilities that are marked ready or approval-gated in the runtime facts.",
                "Do not claim a disabled or unavailable capability is ready.",
                "Explain approval-gated actions as pending until Rust reports execution.",
                "Never claim that an approval was created, a file was written, an app was opened, or a tool was executed unless Rust has provided that concrete tool result for the current turn.",
                "For screen questions, distinguish observation support, observation enabled state, recent capture availability, fresh capture, and vision model availability.",
                "When Rust provides tool or screen results, ground the answer in those results.",
                "For normal conversation, answer naturally without exposing internal implementation details.",
            ],
        },
    }
}

pub fn capability_label(value: &CapabilityToolAvailability) -> &'static str {
    match value.state {
        CapabilityRuntimeState::Unavailable => "not available",
        CapabilityRuntimeState::Disabled => "available but disabled",
        CapabilityRuntimeState::ApprovalGated => "available and approval-gated",
        CapabilityRuntimeState::Ready => "available and ready",
    }
}

fn permission_name(permission: &Permission) -> &'static str {
    match permission {
        Permission::FilesystemRead => "filesystem_read",
        Permission::FilesystemWrite => "filesystem_write",
        Permission::FilesystemSearch => "filesystem_search",
        Permission::TerminalSafe => "terminal_safe",
        Permission::TerminalDangerous => "terminal_dangerous",
        Permission::BrowserRead => "browser_read",
        Permission::BrowserAction => "browser_action",
        Permission::DesktopObserve => "desktop_observe",
        Permission::DesktopControl => "desktop_control",
    }
}
